source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

use_frameworks!

platform :ios, '13.0'

target 'TYMediaPlayer_Example' do
  pod 'TYMediaPlayer', :path => '../'

end
